version: '3.7'
services:  
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: snappay
      POSTGRES_PASSWORD: snappay
      POSTGRES_DB: expensetracker
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-service:  
    build: ./user-service  
    ports:  
      - "8081:8081"  
    depends_on:  
      - db  

  expense-service:  
    build: ./expense-service  
    ports:  
      - "8082:8082"  
    depends_on:  
      - db  
      - user-service  
